# Generated by Django 5.0 on 2023-12-15 19:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('total_download', models.CharField(blank=True, max_length=200, null=True)),
                ('force_update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('first_login_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 16, 0, 39, 38, 393390), null=True)),
                ('last_login_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 16, 0, 39, 38, 393390), null=True)),
                ('device_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.appinfo')),
            ],
        ),
    ]
