# Generated by Django 5.0 on 2024-01-02 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='is_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 23, 14, 19, 454724), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 23, 14, 19, 454724), null=True),
        ),
    ]
