# Generated by Django 5.0 on 2024-01-02 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0003_rename_is_download_appinfo_can_video_download_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appinfo',
            old_name='can_video_download',
            new_name='is_video_download',
        ),
        migrations.AlterField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 23, 22, 45, 996356), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 23, 22, 45, 996356), null=True),
        ),
    ]
