# Generated by Django 5.0 on 2024-01-17 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_rename_can_video_download_appinfo_is_video_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 20, 30, 29, 763672), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 20, 30, 29, 763672), null=True),
        ),
    ]
